### ISSUE TITLE
Need an option to generate documentation with filename of choice 

### ISSUE THREAD

**Issue by ksatchit** [outbit/ansible-docgen#33]
Currently,  ansible-docgen always creates a README.md as the default markdown doc. User should be given a choice to specify a filename of his choice. Something like the below : 

ansible-docgen -f playbook_info 

      ...generates playbook_info.md

In my case, the README is a file containing info about the general purpose of a set of playbooks OR roles in a folder. While I would love to have the doc telling me about the specifics/summary of each playbook/role , I wouldn't want it to replace the README.md

Of course, it could be argued that the original README can be moved to a different filename - but somehow I would like to have original README as _the_ readme a user should be directed to.

**Comment by thedavidwhiteside** [comment]
Adding as a goal for v1.0.0
